export const NAV = [
  ['Use', [
    ['Overview', 'index.html', 'Start the runtime and choose a reading path.'],
    ['CLI', 'cli.html', 'Run examples and inspect local execution.'],
    ['Conversation', 'conversation.html', 'Introduce yourself, use personal references and ask for useful help.'],
    ['API', 'api.html', 'Connect text clients and reuse session results.'],
    ['Response style', 'response-style.html', 'Choose short answers or explanations while retaining audit evidence.'],
    ['Sessions', 'sessions.html', 'Save, isolate and continue symbolic state.']
  ]],
  ['Understand', [
    ['Capabilities', 'capabilities.html', 'Compare demonstrated behavior with remaining limits.'],
    ['Elementary knowledge', 'foundation.html', 'Use base rules, quantities, locations and everyday defaults.'],
    ['Assumptions', 'assumptions.html', 'Inspect attempted meanings and correct their consequences.'],
    ['Architecture', 'architecture.html', 'Follow parsing, circuit execution and reasoning.'],
    ['Book', 'book.html', 'Read the research monograph and operational chapters.'],
    ['Wiki', 'wiki.html', 'Understand canonical project terms.']
  ]],
  ['Develop', [
    ['Learning and packs', 'learning.html', 'Train expressions and submit tested SOP circuits.'],
    ['Elementary evaluation', 'benchmark.html', 'Inspect the fixed corpus and measured capability results.'],
    ['Validation', 'validation.html', 'Repeat the checks and maintain current evidence.'],
    ['Specifications', 'specsLoader.html?spec=matrix.md', 'Read the normative design contracts.']
  ]]
];

// Entry bodies own the canonical explanatory definition. Aliases share one anchor.
export const TERMS = [
  ['sdlm', ['sdlm', 'sd_lm'], 'The technical name sd_lm is displayed as sdlm. Its first letter means Symbolic, Small or Specific, d means Datalog, and lm means Language Model. sdlm is the local symbolic language model implemented in this repository. Users and applications submit supported language tasks, while circuit authors extend its executable competence. The model consists of a runtime, SOP circuit library and selected symbolic state. Its demonstrated language is controlled English; the name does not imply statistical token prediction or unrestricted language understanding.'],
  ['sop-lang', ['SOP Lang'], 'SOP Lang is the visible circuit composition language. Authors declare inputs, named operation nodes, typed arguments and outputs. The VM expands these circuits and executes their dependencies. Grammar, domain competence and persistent semantic state use the same language. Internal Datalog and graph representations are implementation tools, not additional languages required from ordinary authors.'],
  ['semantic-circuit', ['semantic circuit', 'semantic circuits', 'SOP circuit', 'SOP circuits', 'circuit', 'circuits'], 'A semantic circuit is a named SOP graph that consumes values and returns values. A circuit may recognize a construction, build a semantic command, assert domain knowledge, choose another circuit or render an answer. Authors compose circuits from other circuits and generic primitives. Syntax validation and acceptance examples constrain installation, but do not prove correctness for every possible input.'],
  ['primitive', ['primitive', 'primitives'], 'A primitive is a trusted host operation registered in the runtime rather than defined by another SOP circuit. Runtime maintainers use primitives for generic value construction, backend access and structural operations. Effect metadata tells the VM how an operation can interact with state. Linguistic knowledge belongs in circuits; adding a primitive is not a shortcut for embedding a private domain language in JavaScript.'],
  ['virtual-circuit', ['virtual circuit', 'virtual circuits'], 'A virtual circuit is the task-local graph materialized while the VM expands named circuit definitions. Its nodes carry dependencies, values and execution state. The graph can change when calls expand or failed candidates are replaced. It is separate from the reusable library and from the durable session snapshot; continuation restores semantic state, not a paused graph instruction pointer.'],
  ['ssa', ['SSA'], 'Static single assignment means each local wire name is declared once in a circuit frame. Authors refer to a wire with a dollar-prefixed name, and the loader checks that every reference resolves. Expansion gives frames separate namespaces. SSA expresses value dependencies; it does not itself make a stateful operation pure or guarantee that a circuit terminates.'],
  ['epoch', ['epoch', 'epochs'], 'An epoch is one scheduling period in which the active graph structure remains suitable for evaluation. Expansion or rewrite changes that structure and starts a new period. The VM uses epochs to keep structural changes separate from ordinary value propagation. An epoch is an execution concept, not a durable conversation turn or a database revision.'],
  ['activation-projection', ['activation projection', 'activation projections'], 'An activation projection is an inexpensive necessary-condition test extracted from a candidate circuit. The selector uses it to narrow possible work before exact guards run. It must preserve every candidate that could pass the real condition. Conditions whose semantics do not match a typed index key remain predicate checks. Projection improves selection cost; it cannot establish complete semantic correctness.'],
  ['candidate', ['candidate', 'candidates'], 'A candidate is a circuit or interpretation still eligible to solve the current task. Selection narrows a group using activation conditions, and execution confirms applicability. A circuit without activation constraints stays eligible. Search limits can restrict how many candidates are explored. Candidate presence is a possibility, not a committed interpretation or an assertion in the knowledge base.'],
  ['chart-parser', ['chart parser', 'chart parsing'], 'The chart parser recognizes typed grammar symbols over token spans and combines compatible spans into larger constructions. Parsing maintainers use it for compositional recognition beyond specialized sentence circuits. It shares subproblems and retains bounded alternatives. The chart supports the installed grammar only; its presence does not imply that arbitrary English is understood.'],
  ['parse-forest', ['parse forest', 'parse forests'], 'A parse forest records alternative supported parse structures for an input. The language execution path can expose competing meanings rather than choosing one silently. The implementation bounds the retained alternatives, so a forest is not necessarily exhaustive. Semantic execution and transactions determine whether an interpretation can commit knowledge.'],
  ['hypothesis', ['hypothesis', 'hypotheses', 'hypothesis beam'], 'An execution hypothesis is a possible interpretation or circuit path with a score and supporting parse information. The runtime may keep a bounded beam of hypotheses and try them under effect restrictions. Strict ambiguity retains alternatives; conversation mode may select one with a recorded assumption. A conditional missing-premise proposal cites installed rules without asserting its premises. In the research chapters, a scientific hypothesis is a separate proposed claim requiring experiments; neither use means proven competence.'],
  ['knowledge-base', ['knowledge base', 'KB'], 'The knowledge base stores explicit unary and binary assertions and safe positive rules, then computes derived relations. Users change it through semantic commands or circuits. Polarity and qualifiers affect relation identity, and retraction rebuilds closure. Its public snapshot is committed state. It does not store a complete historical source witness for every derived fact.'],
  ['four-valued-status', ['four-state', 'four-valued status', 'four-valued'], 'The four-valued query status records positive and negative support independently. Users can receive supported, refuted, both or unknown outcomes. Both preserves an explicit contradiction without making every statement true; unknown records missing evidence. This status describes the current symbolic store and rules, not a calibrated probability or a claim that the source knowledge is correct.'],
  ['qualifier', ['qualifier', 'qualifiers'], 'A qualifier is an additional semantic distinction on an atom, such as the modal can relation. The knowledge base keeps qualified and unqualified relations separate. Induction and export must preserve this value. A qualifier is part of the relation contract, but the currently supported qualifiers do not provide a complete modal or temporal logic.'],
  ['proof', ['proof', 'proofs', 'provenance'], 'An explanation proof is a reconstructed support tree built from current asserted facts and rules. It lets users inspect why a conclusion follows. Reconstruction has a depth limit and may return a derived marker instead of a complete tree. Provenance more broadly means source and derivation information; the runtime persists interpretation decisions and assertion support IDs, but does not persist complete historical source and derivation witnesses. Aggregate context assumptions are separate from proven dependencies.'],
  ['transaction', ['transaction', 'transactions'], 'A transaction groups symbolic state changes so a request or speculative branch can commit or roll back together. The runtime snapshots knowledge, language, grammar, saved values, interpretation evidence and session settings. Public operations serialize and rollback respects nested scopes. A filesystem session revision adds a separate publication boundary; neither mechanism guarantees rollback of arbitrary external side effects or power-loss durability.'],
  ['effect-analysis', ['effect analysis', 'effects', 'effect'], 'Effect analysis classifies how a primitive or circuit can interact with state. The runtime traverses reachable dependencies, including recursion, and combines pure, read, write or unknown behavior before caching. This controls safe speculation. An unknown effect cannot be treated as pure. The analysis is conservative metadata-based reasoning, not formal verification of arbitrary host code.'],
  ['circuit-pack', ['circuit pack', 'circuit packs'], 'A circuit pack is a directory of named SOP files under circuits, grouped by subdirectories. Authors distribute language and domain competence in packs. Installation validates the combined library and executes incoming bootstraps. HTTP uploads also require acceptance tests in separate trial state. A knowledge-only export is a pack, while a session export additionally captures learned competence and saved values.'],
  ['bootstrap', ['bootstrap', 'bootstraps'], 'A bootstrap is a circuit in the bootstrap group or a group ending in .bootstrap. Initialization and installation run it to register grammar, lexicon or explicit knowledge. Saved sessions restore the authoritative knowledge snapshot after ordinary bootstraps, preserving retractions. A bootstrap is executable setup and participates in validation and transaction boundaries.'],
  ['induction', ['induction', 'circuit induction'], 'Circuit induction compiles surface/canonical example pairs into new executable SOP constructions. A user supplies examples, and the inducer generalizes supported slots while preserving semantic polarity and qualifiers. It validates supplied examples before publishing. This is a bounded symbolic learning procedure; it does not train neural parameters or automatically infer broad competence from an arbitrary corpus.'],
  ['session', ['session', 'sessions'], 'A session is a named independent symbolic state, circuit competence and set of reusable values. Interactive CLI startup resumes the last selected durable session automatically; users can create or select another. API clients supply an ID explicitly. Terminal command recall is stored separately from semantic state and never replays on restoration. A committed SOP revision stores semantics, while JSON retains transport history and its pointer. Sessions isolate runtime state from each other, but the API bearer token grants access to the entire store rather than identifying individual owners.'],
  ['snapshot', ['snapshot', 'snapshots'], 'A snapshot is a representation of symbolic state at a boundary. Runtime snapshots support rollback; durable session snapshots express asserted knowledge and saved values as SOP constructors. Restoring a session rebuilds derived closure and indexes without replaying conversational text. A snapshot depends on the installed base runtime and library and is not a full versioned executable archive.'],
  ['value-reference', ['value reference', 'value references', 'reusable values'], 'A value reference identifies a saved session-local result and optional nested fields. Clients use dot-separated paths through own object properties or array indices. A $ref input passes the structured value directly to a circuit; text bindings accept scalars. Reference lookup evaluates no code and rejects unknown paths. Names can expire when the bounded saved-value store evicts old entries.'],
  ['cnl', ['controlled English', 'controlled language', 'controlled-language', 'CNL'], 'Controlled natural language is the supported subset of English defined by the installed grammar and semantic circuits. Users express explicit statements and questions with testable meanings. Extensions can add constructions, vocabulary and domain behavior. Capitalization and lexical patterns can affect recognition, so a familiar English sentence is not automatically valid input. The example catalog documents representative accepted forms.'],
  ['nlg', ['NLG', 'symbolic generation'], 'Symbolic natural-language generation turns structured answers into controlled text through SOP response circuits. It is used for confirmations, query results, summaries and explanations. The language store supplies display forms. It does not sample an unrestricted vocabulary or provide a general neural writing model.'],
  ['one-language-invariant', ['one-language invariant', 'one-language rule'], 'The one-language invariant requires ordinary competence and composition to remain visible as SOP circuits and typed values. Runtime authors may use Datalog, indexes and graph structures internally. Circuit authors should not need a hidden linguistic string language. Architecture tests enforce known boundaries, but their passing does not prove that every future extension respects the invariant.'],
  ['datalog', ['Datalog'], 'Datalog evaluates finite relational facts and safe rules until no additional tuples appear. sdlm uses it for knowledge closure and candidate selection through a replaceable adapter. The bundled evaluator and external package share regression tests. Negation is represented as explicit support relations in this product, and rule-head variables must be bound in the body. Backend implementation details are not part of the author-facing circuit language.'],
  ['nomatch', ['NoMatch'], 'NoMatch is a controlled failure indicating that an interpretation or circuit does not apply. The VM may roll back that trial and select an alternative. Strict execution reports a language error when all candidates fail. Conversation mode tries bounded SOP fallback and punctuation repair, then returns an unresolved result with a useful clarification if none succeeds. Actual token classifications remain in the structured gap evidence. NoMatch must not leave a failed branch\'s knowledge in the committed state.'],
  ['rewrite', ['rewrite', 'rewrites'], 'A runtime rewrite replaces an unsuccessful active circuit choice with another candidate. It changes the task-local graph and starts a new scheduling epoch. Transactions undo speculative symbolic writes before replacement. General equality saturation and learned graph optimization in the book are research proposals and are not implied by this operational rewrite mechanism.'],
  ['expansion', ['expansion', 'reduction'], 'Expansion replaces a circuit call with its local operation graph and connects inputs and outputs to the parent frame. Reduction returns a completed frame result to its caller. The VM owns this lifecycle, preserving separate SSA namespaces and checking execution budgets. These graph operations are distinct from semantic learning, which changes reusable circuit definitions.'],
  ['fixed-point', ['fixed point'], 'A fixed point is the stage at which another application of the rule evaluator adds no new facts. The knowledge base materializes this closure after assertions and retractions. Finiteness and safe rules support termination for the implemented relational language. Reaching a fixed point does not prove that the asserted world model is complete or factually correct.'],
  ['virtual-machine', ['virtual machine', 'VM'], 'The virtual machine loads a named circuit into a task-local graph, schedules ready operations and expands or rewrites calls as needed. Runtime maintainers own its generic execution rules. It tracks effects, transactions and budgets while SOP definitions supply competence. A session restart creates a new VM execution; it does not continue a suspended host call stack.'],
  ['semantic-command', ['semantic command', 'semantic commands'], 'A semantic command is the typed value produced by parsing and consumed by ExecuteCommand. It identifies an operation such as asserting a fact, adding a rule or asking a question, with its structured payload. Circuit authors construct these values using ordinary SOP calls. Inspecting a parsed command alone does not assert its knowledge, and unsupported commands must fail execution.'],
  ['activation-index', ['activation index', 'activation indexes'], 'An activation index maps inexpensive observations to potentially applicable circuits. The selector uses it before exact candidate evaluation to avoid scanning every specialized circuit. Every indexed condition must be necessary under the real guard semantics. Unconstrained candidates and predicates that cannot be indexed soundly remain eligible through their separate selection paths.'],
  ['assumption', ['assumption', 'assumptions'], 'An assumption is a recorded interpretation decision that was needed to execute an input. It stores an ID, input, original symbol, selected value, category, reason and circuit before execution. Conversation users inspect and reject these decisions. Assertion support sets and saved-value dependencies connect a rejection to knowledge retraction and invalidated references. Heuristic certainty is qualitative, and a conditional missing-premise proposal does not assert its truth. Session context assumptions can be listed separately when their individual contribution to an aggregate has not been established.'],
  ['base-knowledge', ['base knowledge', 'elementary knowledge'], 'Base knowledge is the authored collection of elementary facts and safe rules installed by foundation bootstrap circuits in a fresh session. It supplies familiar categories, purposes, needs and relations used by school-language circuits. Users can inspect and retract this knowledge. Library callers can disable it for evaluation. Restoring a session uses its authoritative snapshot and does not automatically merge newly released base assertions. The collection is a bounded ordinary-world model with explicit exceptions, not a complete encyclopedia.'],
  ['benchmark', ['benchmark', 'benchmarks'], 'A benchmark is a versioned set of inputs and expected outputs used to measure the runtime. The early-school corpus has 88 authored English cases, divided equally between development and reserved evaluation across eleven domains. The runner uses a fresh runtime for each case and scores typed answers exactly. Reports include actual answers, assumptions and fingerprints. Expected answers never supply ordinary runtime responses. The reserved split shares authorship with the development set and does not establish blind generalization or equivalence to a human age.'],
  ['response-style', ['response style', 'response preferences', 'verbosity'], 'Response style is a session-local SOP setting that selects answer-only or explained conversation text. Users change it through CLI commands, supported input sentences or the chat verbosity extension. The setting is transactional and persists as SOP with the session. Both styles preserve structured answers, assumptions and correction evidence; a short Yes can still depend on a heuristic. Strict execution bypasses conversation formatting, and compact presentation does not reduce the retained audit payload.'],
  ['current-speaker', ['current speaker'], 'The current speaker is the entity selected by the latest supported introduction in one conversation session. SOP circuits record the selection as conversation_speaker(_conversation, name) and retain introduced(name) as introduction evidence. First-person statements and questions use that relation and expose their resolution decision. Inferred names and dependent assertions participate in assumption rejection; explicit independent support survives. A session restart restores these facts without replaying introductions. Changing the current speaker preserves earlier facts about other entities. This convention does not authenticate an account or establish the real identity of the person typing.'],
  ['atom', ['atom', 'atoms'], 'An atom is a typed unary or binary relation with a predicate, argument terms, polarity and optional qualifier. Users express atoms through supported language, and circuit authors construct them directly. Ground atoms can be asserted as facts; variable-bearing atoms occur in safe rules and queries. Atoms do not encode an entire temporal or source-attribution model.']
];
